(function referencePriceDataModule(global) {
  // Manual reference snapshots for development/testing.
  // These are observed/reference prices, not live checkout prices.
  const REFERENCE_PRICES = [
    {
      storeId: "bonus",
      storeName: "Bónus",
      query: "nautahakk",
      productName: "SS ungnautahakk 490 gr",
      normalizedName: "nautahakk",
      price: 1659,
      sizeLabel: "490 gr",
      unitPrice: 3386,
      sourceName: "Neytandinn",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
    },
    {
      storeId: "bonus",
      storeName: "Bónus",
      query: "nautahakk",
      productName: "Ungnautahakk 500 gr",
      normalizedName: "nautahakk",
      price: 1689,
      sizeLabel: "500 gr",
      unitPrice: 3378,
      sourceName: "ASÍ",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
    },
    {
      storeId: "kronan",
      storeName: "Krónan",
      query: "nautahakk",
      productName: "Ungnautahakk 500 gr",
      normalizedName: "nautahakk",
      price: 1749,
      sizeLabel: "500 gr",
      unitPrice: 3498,
      sourceName: "Neytandinn",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
    },
    {
      storeId: "hagkaup",
      storeName: "Hagkaup",
      query: "nautahakk",
      productName: "Ungnautahakk 500 gr",
      normalizedName: "nautahakk",
      price: 1998,
      sizeLabel: "500 gr",
      unitPrice: 3996,
      sourceName: "Neytandinn",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
    },
    {
      storeId: "netto",
      storeName: "Nettó",
      query: "nautahakk",
      productName: "Ungnautahakk 500 gr",
      normalizedName: "nautahakk",
      price: 1799,
      sizeLabel: "500 gr",
      unitPrice: 3598,
      sourceName: "ASÍ",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
    },
    {
      storeId: "pris",
      storeName: "Prís",
      query: "nautahakk",
      productName: "Nautahakk 500 gr",
      normalizedName: "nautahakk",
      price: 1699,
      sizeLabel: "500 gr",
      unitPrice: 3398,
      sourceName: "Nappið",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "low",
    },
    {
      storeId: "bonus",
      storeName: "Bónus",
      query: "egg",
      productName: "Egg 10 stk",
      normalizedName: "egg",
      price: 699,
      sizeLabel: "10 stk",
      unitPrice: 69.9,
      sourceName: "Neytandinn",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
    },
    {
      storeId: "bonus",
      storeName: "Bónus",
      query: "mjólk",
      productName: "Nýmjólk 1 L",
      normalizedName: "mjolk",
      price: 189,
      sizeLabel: "1 L",
      unitPrice: 189,
      sourceName: "Neytandinn",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
    },
    {
      storeId: "bonus",
      storeName: "Bónus",
      query: "hafrar",
      productName: "Hafrar 1 kg",
      normalizedName: "hafrar",
      price: 349,
      sizeLabel: "1 kg",
      unitPrice: 349,
      sourceName: "ASÍ",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
    },
    {
      storeId: "bonus",
      storeName: "Bónus",
      query: "hrísgrjón",
      productName: "Hrísgrjón 1 kg",
      normalizedName: "hrisgrjon",
      price: 399,
      sizeLabel: "1 kg",
      unitPrice: 399,
      sourceName: "Neytandinn",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
    },
    {
      storeId: "bonus",
      storeName: "Bónus",
      query: "pasta",
      productName: "Pasta 500 gr",
      normalizedName: "pasta",
      price: 259,
      sizeLabel: "500 gr",
      unitPrice: 518,
      sourceName: "ASÍ",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
    },
    {
      storeId: "bonus",
      storeName: "Bónus",
      query: "kjúklingabringur",
      productName: "Kjúklingabringur 1 kg",
      normalizedName: "kjuklingabringur",
      price: 2399,
      sizeLabel: "1 kg",
      unitPrice: 2399,
      sourceName: "Neytandinn",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
    },
    {
      storeId: "bonus",
      storeName: "Bónus",
      query: "skyr",
      productName: "Skyr 500 gr",
      normalizedName: "skyr",
      price: 449,
      sizeLabel: "500 gr",
      unitPrice: 898,
      sourceName: "Neytandinn",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
    },
  ];

  global.MatvalReferencePriceData = { REFERENCE_PRICES };

  if (typeof module !== "undefined") {
    module.exports = { REFERENCE_PRICES };
  }
})(typeof window !== "undefined" ? window : globalThis);
