(function referencePriceDataModule(global) {
  // Manual reference snapshots for development/testing.
  // These are observed/reference prices, not live checkout prices.
  const REFERENCE_PRICES = [
    {
      storeId: "bonus",
      storeName: "Bónus",
      query: "nautahakk",
      productName: "SS ungnautahakk 490 gr",
      normalizedName: "nautahakk",
      aliases: ["hakk", "nautahakk", "ungnautahakk", "minced beef"],
      price: 1659,
      sizeLabel: "490 gr",
      unitPrice: 3386,
      sourceName: "Neytandinn",
      sourceType: "reference",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
      category: "protein",
    },
    {
      storeId: "bonus",
      storeName: "Bónus",
      query: "nautahakk",
      productName: "Ungnautahakk 500 gr",
      normalizedName: "nautahakk",
      aliases: ["hakk", "nautahakk", "ungnautahakk", "minced beef"],
      price: 1689,
      sizeLabel: "500 gr",
      unitPrice: 3378,
      sourceName: "ASÍ",
      sourceType: "reference",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
      category: "protein",
    },
    {
      storeId: "kronan",
      storeName: "Krónan",
      query: "nautahakk",
      productName: "Ungnautahakk 500 gr",
      normalizedName: "nautahakk",
      aliases: ["hakk", "nautahakk", "ungnautahakk", "minced beef"],
      price: 1749,
      sizeLabel: "500 gr",
      unitPrice: 3498,
      sourceName: "Neytandinn",
      sourceType: "reference",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
      category: "protein",
    },
    {
      storeId: "kronan",
      storeName: "Krónan",
      query: "laukur",
      productName: "Laukur 1 kg",
      normalizedName: "laukur",
      aliases: ["laukur", "onion"],
      price: 249,
      sizeLabel: "1 kg",
      unitPrice: 249,
      sourceName: "Krónan cached",
      sourceType: "store",
      priceSource: "store",
      observedAt: "2026-06-18",
      fetchedAt: "2026-06-18",
      confidence: "medium",
      category: "produce",
    },
    {
      storeId: "kronan",
      storeName: "Krónan",
      query: "hvítlaukur",
      productName: "Hvítlaukur 1 stk",
      normalizedName: "hvitlaukur",
      aliases: ["hvitlaukur", "hvítlaukur", "garlic"],
      price: 149,
      sizeLabel: "1 stk",
      unitPrice: 149,
      sourceName: "Krónan cached",
      sourceType: "store",
      priceSource: "store",
      observedAt: "2026-06-18",
      fetchedAt: "2026-06-18",
      confidence: "medium",
      category: "produce",
    },
    {
      storeId: "kronan",
      storeName: "Krónan",
      query: "sojasósa",
      productName: "Sojasósa 150 ml",
      normalizedName: "sojasosa",
      aliases: ["sojasosa", "sojasósa", "soy sauce"],
      price: 399,
      sizeLabel: "150 ml",
      unitPrice: 2660,
      sourceName: "Krónan cached",
      sourceType: "store",
      priceSource: "store",
      observedAt: "2026-06-18",
      fetchedAt: "2026-06-18",
      confidence: "medium",
      category: "pantry",
    },
    {
      storeId: "kronan",
      storeName: "Krónan",
      query: "matarolía",
      productName: "Matarolía 1 L",
      normalizedName: "matarolia",
      aliases: ["matarolia", "matarolía", "oil", "olia", "olía"],
      price: 699,
      sizeLabel: "1 L",
      unitPrice: 699,
      sourceName: "Krónan cached",
      sourceType: "store",
      priceSource: "store",
      observedAt: "2026-06-18",
      fetchedAt: "2026-06-18",
      confidence: "medium",
      category: "pantry",
    },
    {
      storeId: "kronan",
      storeName: "Krónan",
      query: "krydd",
      productName: "Krydd 1 stk",
      normalizedName: "krydd",
      aliases: ["krydd", "spices", "spice"],
      price: 399,
      sizeLabel: "1 stk",
      unitPrice: 399,
      sourceName: "Krónan cached",
      sourceType: "store",
      priceSource: "store",
      observedAt: "2026-06-18",
      fetchedAt: "2026-06-18",
      confidence: "low",
      category: "pantry",
    },
    {
      storeId: "hagkaup",
      storeName: "Hagkaup",
      query: "nautahakk",
      productName: "Ungnautahakk 500 gr",
      normalizedName: "nautahakk",
      aliases: ["hakk", "nautahakk", "ungnautahakk", "minced beef"],
      price: 1998,
      sizeLabel: "500 gr",
      unitPrice: 3996,
      sourceName: "Neytandinn",
      sourceType: "reference",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
      category: "protein",
    },
    {
      storeId: "netto",
      storeName: "Nettó",
      query: "nautahakk",
      productName: "Ungnautahakk 500 gr",
      normalizedName: "nautahakk",
      aliases: ["hakk", "nautahakk", "ungnautahakk", "minced beef"],
      price: 1799,
      sizeLabel: "500 gr",
      unitPrice: 3598,
      sourceName: "ASÍ",
      sourceType: "reference",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
      category: "protein",
    },
    {
      storeId: "pris",
      storeName: "Prís",
      query: "nautahakk",
      productName: "Nautahakk 500 gr",
      normalizedName: "nautahakk",
      aliases: ["hakk", "nautahakk", "ungnautahakk", "minced beef"],
      price: 1699,
      sizeLabel: "500 gr",
      unitPrice: 3398,
      sourceName: "Nappið",
      sourceType: "reference",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "low",
      category: "protein",
    },
    {
      storeId: "bonus",
      storeName: "Bónus",
      query: "egg",
      productName: "Egg 10 stk",
      normalizedName: "egg",
      aliases: ["egg", "eggs", "egg 10 stk"],
      price: 699,
      sizeLabel: "10 stk",
      unitPrice: 69.9,
      sourceName: "Neytandinn",
      sourceType: "reference",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
      category: "protein",
    },
    {
      storeId: "bonus",
      storeName: "Bónus",
      query: "mjólk",
      productName: "Nýmjólk 1 L",
      normalizedName: "mjolk",
      aliases: ["mjolk", "mjólk", "nymjolk", "nýmjólk", "milk"],
      price: 189,
      sizeLabel: "1 L",
      unitPrice: 189,
      sourceName: "Neytandinn",
      sourceType: "reference",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
      category: "dairy",
    },
    {
      storeId: "bonus",
      storeName: "Bónus",
      query: "hafrar",
      productName: "Hafrar 1 kg",
      normalizedName: "hafrar",
      aliases: ["hafrar", "haframjol", "haframjöl", "oats"],
      price: 349,
      sizeLabel: "1 kg",
      unitPrice: 349,
      sourceName: "ASÍ",
      sourceType: "reference",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
      category: "pantry",
    },
    {
      storeId: "bonus",
      storeName: "Bónus",
      query: "hrísgrjón",
      productName: "Hrísgrjón 1 kg",
      normalizedName: "hrisgrjon",
      aliases: ["hrisgrjon", "hrísgrjón", "grjon", "grjón", "rice"],
      price: 399,
      sizeLabel: "1 kg",
      unitPrice: 399,
      sourceName: "Neytandinn",
      sourceType: "reference",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
      category: "pantry",
    },
    {
      storeId: "bonus",
      storeName: "Bónus",
      query: "pasta",
      productName: "Pasta 500 gr",
      normalizedName: "pasta",
      aliases: ["pasta"],
      price: 259,
      sizeLabel: "500 gr",
      unitPrice: 518,
      sourceName: "ASÍ",
      sourceType: "reference",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
      category: "pantry",
    },
    {
      storeId: "bonus",
      storeName: "Bónus",
      query: "kjúklingabringur",
      productName: "Kjúklingabringur 1 kg",
      normalizedName: "kjuklingabringur",
      aliases: ["kjuklingabringur", "kjúklingabringur", "kjuklingur", "kjúklingur", "chicken breast"],
      price: 2399,
      sizeLabel: "1 kg",
      unitPrice: 2399,
      sourceName: "Neytandinn",
      sourceType: "reference",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
      category: "protein",
    },
    {
      storeId: "bonus",
      storeName: "Bónus",
      query: "skyr",
      productName: "Skyr 500 gr",
      normalizedName: "skyr",
      aliases: ["skyr", "yogurt", "jogurt"],
      price: 449,
      sizeLabel: "500 gr",
      unitPrice: 898,
      sourceName: "Neytandinn",
      sourceType: "reference",
      priceSource: "reference",
      observedAt: "2026-06-18",
      confidence: "medium",
      category: "dairy",
    },
  ];

  global.MatvalReferencePriceData = { REFERENCE_PRICES };

  if (typeof module !== "undefined") {
    module.exports = { REFERENCE_PRICES };
  }
})(typeof window !== "undefined" ? window : globalThis);
